apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deploy
  labels:
    app: finalEx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: devoops93/todo-app:latest
          ports:
            - containerPort: 5000
